### ISSUE TITLE
No modules named 'gw2api.objects'

### ISSUE THREAD

**Issue by drob0009** [JuxhinDB/gw2-api-interface#5]
Installing from source I get the following error:
```
guildwars2_api_client-0.5.0-py3.6.egg\gw2api\__init__.py", line 74, in __build_object_clients
ModuleNotFoundError: No module named 'gw2api.objects'
```

Simple solution is to simply add an empty `__init__.py` to the gw2api/objects folder.

**Comment by JuxhinDB** [comment]
It's kind of funny how silly I am to not have remembered that modules require empty __init__ files to be importable. So used to IDEs just automagically throwing in an empty __init__ for me. :-)

I have pushed the fix and will be uploading to PyPi shortly. Leaving open to confirm with you that it works. 

EDIT: Confirmed the push to [pypi](https://pypi.org/project/GuildWars2-API-Client/0.5.3/) can you please confirm it works @l0phty

**Comment by drob0009** [comment]
Hmm, it doesn't look resolved on my end. I removed my old installation and reinstalled version 0.5.5 and still getting the same error. Also downloaded fresh copy of source and tried installation from source but get the same error which is bizzare as I can _see_ `__init__.py` in the objects folder.

**Comment by drob0009** [comment]
Note for your own testing I can import gw2api just fine, its when I init an instance of GuildWars2Client that I trigger the error.

**Comment by shoeffner** [comment]
The objects directory seems not to be included:
```
$ ls ${HOME}/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages/gw2api
__init__.py __pycache__
```
Hm, somehow I thought this was fixed, but maybe I installed from the git source then...

**Comment by shoeffner** [comment]
See also: https://github.com/JuxhinDB/gw2-api-interface/pull/3#issuecomment-395036611

**Comment by JuxhinDB** [comment]
@l0phty @shoeffner -- I believe I have found out the issue (?) 

I have pushed an updated version to PyPi, version 0.5.7, could someone please run the following:

```
pip install -v GuildWars2-API-Client --no-cache-dir
python
>>> from gw2api import GuildWars2Client
>>>
>>> api = GuildWars2Client()
>>> print(api.build.get())
```

And provide me with the output. Should be working now. If it does, I can go ahead and push the commit.

**Comment by shoeffner** [comment]
It works! Thanks a lot.

```
Created temporary directory: /private/var/folders/mb/nwwt_8ps1g7_7ml5wcpzx_v80000gn/T/pip-ephem-wheel-cache-ok1clg12
Created temporary directory: /private/var/folders/mb/nwwt_8ps1g7_7ml5wcpzx_v80000gn/T/pip-install-eochkr2m
Collecting GuildWars2-API-Client
  1 location(s) to search for versions of GuildWars2-API-Client:
  * https://pypi.org/simple/guildwars2-api-client/
  Getting page https://pypi.org/simple/guildwars2-api-client/
  Starting new HTTPS connection (1): pypi.org
  https://pypi.org:443 "GET /simple/guildwars2-api-client/ HTTP/1.1" 200 600
  Analyzing links from page https://pypi.org/simple/guildwars2-api-client/
    Skipping link https://files.pythonhosted.org/packages/9c/92/cc10f82c809e16fea9eab44980704b5a09e9ee50b9190af86fca7497be80/GuildWars2%20API%20Client-0.5.2.tar.gz#sha256=8ba2bc5ee17ea55281e68636d53a3bf5de6d20b8e6a620ab1bf049ab4b0c1b5c (from https://pypi.org/simple/guildwars2-api-client/); wrong project name (not GuildWars2-API-Client)
    Skipping link https://files.pythonhosted.org/packages/8e/dc/cd2c4b2823b440ef82f2f9e188b6cafa586f0b6c78e088fdebd26b0aabc1/GuildWars2%20API%20Client-0.5.3.tar.gz#sha256=9f82b920ad45e2d86b596affeffea517e11772e051e30b7eb32faaf3191a3652 (from https://pypi.org/simple/guildwars2-api-client/); wrong project name (not GuildWars2-API-Client)
    Found link https://files.pythonhosted.org/packages/f1/54/3c33d6141069443a2c5d295bcaf391f87490f96b9eea32f44ae2dbafaaba/GuildWars2-API-Client-0.5.5.tar.gz#sha256=2936b7d54f11205b13aeadc4c5b0f9624d36680da064dd6152bcb37583b7f4d8 (from https://pypi.org/simple/guildwars2-api-client/), version: 0.5.5
    Found link https://files.pythonhosted.org/packages/80/30/3bb3a3b1a6e94bfe4b4b90afbfe160841c7f279f0cfd5f320ef56b859966/GuildWars2-API-Client-0.5.7.tar.gz#sha256=d38fa53c3220b5a550965fabdaead917c8f7d3f0a92f069de6a3770f41cae9e9 (from https://pypi.org/simple/guildwars2-api-client/), version: 0.5.7
  Using version 0.5.7 (newest of versions: 0.5.5, 0.5.7)
  Created temporary directory: /private/var/folders/mb/nwwt_8ps1g7_7ml5wcpzx_v80000gn/T/pip-unpack-4t2l8u5b
  Starting new HTTPS connection (1): files.pythonhosted.org
  https://files.pythonhosted.org:443 "GET /packages/80/30/3bb3a3b1a6e94bfe4b4b90afbfe160841c7f279f0cfd5f320ef56b859966/GuildWars2-API-Client-0.5.7.tar.gz HTTP/1.1" 200 10260
  Downloading https://files.pythonhosted.org/packages/80/30/3bb3a3b1a6e94bfe4b4b90afbfe160841c7f279f0cfd5f320ef56b859966/GuildWars2-API-Client-0.5.7.tar.gz
  Downloading from URL https://files.pythonhosted.org/packages/80/30/3bb3a3b1a6e94bfe4b4b90afbfe160841c7f279f0cfd5f320ef56b859966/GuildWars2-API-Client-0.5.7.tar.gz#sha256=d38fa53c3220b5a550965fabdaead917c8f7d3f0a92f069de6a3770f41cae9e9 (from https://pypi.org/simple/guildwars2-api-client/)
  Running setup.py (path:/private/var/folders/mb/nwwt_8ps1g7_7ml5wcpzx_v80000gn/T/pip-install-eochkr2m/GuildWars2-API-Client/setup.py) egg_info for package GuildWars2-API-Client
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/GuildWars2_API_Client.egg-info
    writing pip-egg-info/GuildWars2_API_Client.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/GuildWars2_API_Client.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/GuildWars2_API_Client.egg-info/requires.txt
    writing top-level names to pip-egg-info/GuildWars2_API_Client.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/GuildWars2_API_Client.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/GuildWars2_API_Client.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/GuildWars2_API_Client.egg-info/SOURCES.txt'
  Source in /private/var/folders/mb/nwwt_8ps1g7_7ml5wcpzx_v80000gn/T/pip-install-eochkr2m/GuildWars2-API-Client has version 0.5.7, which satisfies requirement GuildWars2-API-Client from https://files.pythonhosted.org/packages/80/30/3bb3a3b1a6e94bfe4b4b90afbfe160841c7f279f0cfd5f320ef56b859966/GuildWars2-API-Client-0.5.7.tar.gz#sha256=d38fa53c3220b5a550965fabdaead917c8f7d3f0a92f069de6a3770f41cae9e9
Requirement already satisfied: requests in /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages (from GuildWars2-API-Client) (2.19.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages (from requests->GuildWars2-API-Client) (3.0.4)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages (from requests->GuildWars2-API-Client) (1.23)
Requirement already satisfied: certifi>=2017.4.17 in /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages (from requests->GuildWars2-API-Client) (2018.4.16)
Requirement already satisfied: idna<2.8,>=2.5 in /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages (from requests->GuildWars2-API-Client) (2.7)
Installing collected packages: GuildWars2-API-Client
  Created temporary directory: /private/var/folders/mb/nwwt_8ps1g7_7ml5wcpzx_v80000gn/T/pip-record-ltkcls4k
  Running setup.py install for GuildWars2-API-Client ...     Running command /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/mb/nwwt_8ps1g7_7ml5wcpzx_v80000gn/T/pip-install-eochkr2m/GuildWars2-API-Client/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/mb/nwwt_8ps1g7_7ml5wcpzx_v80000gn/T/pip-record-ltkcls4k/install-record.txt --single-version-externally-managed --compile --install-headers /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/bin/../include/site/python3.6/GuildWars2-API-Client
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/gw2api
    copying gw2api/__init__.py -> build/lib/gw2api
    creating build/lib/gw2api/objects
    copying gw2api/objects/base_object.py -> build/lib/gw2api/objects
    copying gw2api/objects/__init__.py -> build/lib/gw2api/objects
    creating build/lib/gw2api/objects/api_version_2
    copying gw2api/objects/api_version_2/__init__.py -> build/lib/gw2api/objects/api_version_2
    creating build/lib/gw2api/objects/api_version_1
    copying gw2api/objects/api_version_1/__init__.py -> build/lib/gw2api/objects/api_version_1
    running install_lib
    creating /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages/gw2api
    copying build/lib/gw2api/__init__.py -> /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages/gw2api
    creating /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages/gw2api/objects
    creating /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages/gw2api/objects/api_version_2
    copying build/lib/gw2api/objects/api_version_2/__init__.py -> /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages/gw2api/objects/api_version_2
    copying build/lib/gw2api/objects/base_object.py -> /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages/gw2api/objects
    copying build/lib/gw2api/objects/__init__.py -> /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages/gw2api/objects
    creating /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages/gw2api/objects/api_version_1
    copying build/lib/gw2api/objects/api_version_1/__init__.py -> /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages/gw2api/objects/api_version_1
    byte-compiling /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages/gw2api/__init__.py to __init__.cpython-36.pyc
    byte-compiling /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages/gw2api/objects/api_version_2/__init__.py to __init__.cpython-36.pyc
    byte-compiling /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages/gw2api/objects/base_object.py to base_object.cpython-36.pyc
    byte-compiling /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages/gw2api/objects/__init__.py to __init__.cpython-36.pyc
    byte-compiling /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages/gw2api/objects/api_version_1/__init__.py to __init__.cpython-36.pyc
    running install_egg_info
    running egg_info
    writing GuildWars2_API_Client.egg-info/PKG-INFO
    writing dependency_links to GuildWars2_API_Client.egg-info/dependency_links.txt
    writing requirements to GuildWars2_API_Client.egg-info/requires.txt
    writing top-level names to GuildWars2_API_Client.egg-info/top_level.txt
    reading manifest file 'GuildWars2_API_Client.egg-info/SOURCES.txt'
    writing manifest file 'GuildWars2_API_Client.egg-info/SOURCES.txt'
    Copying GuildWars2_API_Client.egg-info to /Users/shoeffner/.local/share/virtualenvs/GW2Ctest/lib/python3.6/site-packages/GuildWars2_API_Client-0.5.7-py3.6.egg-info
    running install_scripts
    writing list of installed files to '/private/var/folders/mb/nwwt_8ps1g7_7ml5wcpzx_v80000gn/T/pip-record-ltkcls4k/install-record.txt'
done
  Removing source in /private/var/folders/mb/nwwt_8ps1g7_7ml5wcpzx_v80000gn/T/pip-install-eochkr2m/GuildWars2-API-Client
Successfully installed GuildWars2-API-Client-0.5.7
Cleaning up...
```
and
```
{'id': 89447}
```

**Comment by JuxhinDB** [comment]
Should be fixed as of https://github.com/JuxhinDB/gw2-api-interface/commit/0f59142ef05e7b574de769381f2e316de9d0b47f

Closing issue
